// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q5_0.cuh"
#include "../fattn-mma-f16.cuh"

#if GGML_CUDA_FA_Q5_0_Q5_0
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q5_0, 256, 256, 8, 8);
#endif // GGML_CUDA_FA_Q5_0_Q5_0
