// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q8_0.cuh"
#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q8_0, 256, 256, 4, 8);
DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q8_0, 512, 512, 4, 8);
