// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-quant-q4_0.cuh"
#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_QUANT_CASE(GGML_TYPE_Q4_0, 256, 256, 16, 2);
